# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 1

before:
  hooks:
    - go mod tidy

builds:
  - binary: xx
    ldflags:
        - "-s -w"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    flags: -trimpath
#  - binary: xx
#    ldflags:
#        - "-H=windowsgui -s -w"
#    env:
#      - CGO_ENABLED=1
#    goos:
#      - windows
#    goarch:
#      - amd64
#    flags: -trimpath

archives:
  - format: tar.gz
    name_template: >-
      {{- .ProjectName }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
